#fixing php storm unit test runner
#php /work/geonames/tests/_fix/phpStormTestRun.php
#php vendor/bin/codecept run unit
#php vendor/bin/codecept run unit --env=stage
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed

#php vendor/bin/codecept run unit --coverage --html
coverage:
    enabled: true
    include:
        - app/*
        - bootstrap/*
        - bootstrap.php
        - console.php
        - jsonService.php
        - index.php
    exclude:
        - app/Models/*
        - app/Exception/*
