version: "3.3"

services:
    codeception-test-engine:
        hostname: codeception-test-engine
        container_name: codeception-test-engine
        build:
            ./.docker
        volumes:
            - .:/www/default:cached
            - $HOME/.composer:$HOME/.composer:cached
            - /opt/phpstorm-coverage/:/opt/phpstorm-coverage/:cached
        ports:
            - "8888:80"
        expose:
            - 8888
        environment:
            - VIRTUAL_HOST=codeception-test-engine.local
            - HTTPS_METHOD=noredirect
            - APACHE_DOCUMENT_ROOT=/www/default
            - HOME=$HOME
            - KERNEL_CLASS_NAME=Kernel

networks:
    default:
        external:
            name: local.net
